package main

import (
	"bytes"
	"compress/flate"
	"compress/gzip"
	"context"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"mailcli/internal/cli"
)

const (
	schemaDirectory = "internal/cli/schemas"
	payloadPath     = "internal/cli/schema_payload_generated.go"
)

type schemaDefinition struct {
	ID     string
	Schema json.RawMessage
}

type publishedCommand struct {
	ID     string          `json:"id"`
	Schema json.RawMessage `json:"schema"`
}

type capabilitiesResponse struct {
	Data struct {
		Capabilities struct {
			Commands []publishedCommand `json:"commands"`
		} `json:"capabilities"`
	} `json:"data"`
}

func main() {
	if len(os.Args) != 2 {
		fail("usage: go run ./scripts/utils/generate-command-schemas.go --bootstrap|--generate|--check")
	}
	var err error
	switch os.Args[1] {
	case "--bootstrap":
		err = bootstrapSchemas()
	case "--generate":
		var source []byte
		source, err = generatedPayloadSource()
		if err == nil {
			_, err = os.Stdout.Write(source)
		}
	case "--check":
		err = checkGeneratedPayload()
	default:
		fail("expected --bootstrap, --generate, or --check")
	}
	if err != nil {
		fail(err.Error())
	}
}

func fail(message string) {
	fmt.Fprintln(os.Stderr, message)
	os.Exit(1)
}

func bootstrapSchemas() error {
	definitions, err := runtimeSchemas()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(schemaDirectory, 0o755); err != nil {
		return fmt.Errorf("create schema directory: %w", err)
	}
	entries, err := os.ReadDir(schemaDirectory)
	if err != nil {
		return fmt.Errorf("read schema directory: %w", err)
	}
	if len(entries) != 0 {
		return fmt.Errorf("refusing to bootstrap into non-empty %s", schemaDirectory)
	}
	for _, command := range definitions {
		path := filepath.Join(schemaDirectory, command.ID+".json")
		var readable bytes.Buffer
		if err := json.Indent(&readable, command.Schema, "", "  "); err != nil {
			return fmt.Errorf("format %s schema: %w", command.ID, err)
		}
		readable.WriteByte('\n')
		file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
		if err != nil {
			return fmt.Errorf("create %s: %w", path, err)
		}
		if _, err := file.Write(readable.Bytes()); err != nil {
			_ = file.Close()
			return fmt.Errorf("write %s: %w", path, err)
		}
		if err := file.Close(); err != nil {
			return fmt.Errorf("close %s: %w", path, err)
		}
	}
	if _, err := fmt.Fprintf(os.Stdout, "bootstrapped %d command schemas in %s\n", len(definitions), schemaDirectory); err != nil {
		return fmt.Errorf("write bootstrap summary: %w", err)
	}
	return nil
}

func checkGeneratedPayload() error {
	want, err := generatedPayloadSource()
	if err != nil {
		return err
	}
	got, err := os.ReadFile(payloadPath)
	if err != nil {
		return fmt.Errorf("read generated payload: %w", err)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("%s is stale; regenerate with --generate and review the output", payloadPath)
	}
	return nil
}

func generatedPayloadSource() ([]byte, error) {
	if err := verifySchemaInventory(); err != nil {
		return nil, err
	}
	definitions, err := readSchemas()
	if err != nil {
		return nil, err
	}
	var payload bytes.Buffer
	for _, definition := range definitions {
		var compact bytes.Buffer
		if err := json.Compact(&compact, definition.Schema); err != nil {
			return nil, fmt.Errorf("compact %s schema: %w", definition.ID, err)
		}
		payload.Write(compact.Bytes())
		payload.WriteByte('\n')
	}
	var compressed bytes.Buffer
	writer, err := gzip.NewWriterLevel(&compressed, flate.BestCompression)
	if err != nil {
		return nil, fmt.Errorf("create schema gzip writer: %w", err)
	}
	if _, err := writer.Write(payload.Bytes()); err != nil {
		return nil, fmt.Errorf("compress command schemas: %w", err)
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("finish command schema compression: %w", err)
	}

	var source strings.Builder
	source.WriteString("// Code generated by scripts/utils/generate-command-schemas.go; DO NOT EDIT.\n\n")
	source.WriteString("package cli\n\nconst schemaPayloadGZIP =\n")
	data := compressed.Bytes()
	const chunkSize = 48
	for offset := 0; offset < len(data); offset += chunkSize {
		end := min(offset+chunkSize, len(data))
		source.WriteString("\t\"")
		for _, value := range data[offset:end] {
			fmt.Fprintf(&source, "\\x%02x", value)
		}
		source.WriteByte('"')
		if end < len(data) {
			source.WriteString(" +")
		}
		source.WriteByte('\n')
	}
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated schema payload: %w", err)
	}
	return formatted, nil
}

func verifySchemaInventory() error {
	definitions, err := readSchemas()
	if err != nil {
		return err
	}
	runtime, err := runtimeSchemas()
	if err != nil {
		return err
	}
	if len(definitions) != len(runtime) {
		return fmt.Errorf("schema file count is %d; published command count is %d", len(definitions), len(runtime))
	}
	known := make(map[string]struct{}, len(definitions))
	for _, definition := range definitions {
		known[definition.ID] = struct{}{}
	}
	for _, command := range runtime {
		if _, exists := known[command.ID]; !exists {
			return fmt.Errorf("published command %s has no per-command schema file", command.ID)
		}
	}
	return nil
}

func readSchemas() ([]schemaDefinition, error) {
	entries, err := os.ReadDir(schemaDirectory)
	if err != nil {
		return nil, fmt.Errorf("read schema directory: %w", err)
	}
	definitions := make([]schemaDefinition, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			return nil, fmt.Errorf("unexpected entry in %s: %s", schemaDirectory, entry.Name())
		}
		path := filepath.Join(schemaDirectory, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", path, err)
		}
		var identity struct {
			ID string `json:"id"`
		}
		if err := json.Unmarshal(data, &identity); err != nil {
			return nil, fmt.Errorf("decode %s: %w", path, err)
		}
		commandID, versioned := strings.CutSuffix(identity.ID, "@v1")
		if !versioned || commandID == "" || commandID+".json" != entry.Name() {
			return nil, fmt.Errorf("schema ID %q does not match filename %s", identity.ID, entry.Name())
		}
		if !json.Valid(data) {
			return nil, fmt.Errorf("schema %s is invalid", identity.ID)
		}
		definitions = append(definitions, schemaDefinition{ID: commandID, Schema: data})
	}
	if len(definitions) == 0 {
		return nil, fmt.Errorf("no command schemas found in %s", schemaDirectory)
	}
	sort.Slice(definitions, func(left, right int) bool {
		return definitions[left].ID < definitions[right].ID
	})
	return definitions, nil
}

func runtimeSchemas() ([]publishedCommand, error) {
	var stdout bytes.Buffer
	var stderr bytes.Buffer
	if code := cli.Run(context.Background(), nil, []string{"capabilities", "--json"}, &stdout, &stderr); code != 0 {
		return nil, fmt.Errorf("read published command schemas: exit %d: %s", code, strings.TrimSpace(stderr.String()))
	}
	var response capabilitiesResponse
	if err := json.Unmarshal(stdout.Bytes(), &response); err != nil {
		return nil, fmt.Errorf("decode published command schemas: %w", err)
	}
	if len(response.Data.Capabilities.Commands) == 0 {
		return nil, fmt.Errorf("published command schema list is empty")
	}
	seen := make(map[string]struct{}, len(response.Data.Capabilities.Commands))
	for _, command := range response.Data.Capabilities.Commands {
		if command.ID == "" || len(command.Schema) == 0 {
			return nil, fmt.Errorf("published command has an empty ID or schema")
		}
		if _, exists := seen[command.ID]; exists {
			return nil, fmt.Errorf("published command ID %s is repeated", command.ID)
		}
		seen[command.ID] = struct{}{}
		var identity struct {
			ID string `json:"id"`
		}
		if err := json.Unmarshal(command.Schema, &identity); err != nil {
			return nil, fmt.Errorf("decode %s schema identity: %w", command.ID, err)
		}
		if identity.ID != command.ID+"@v1" {
			return nil, fmt.Errorf("published command %s has schema identity %s", command.ID, identity.ID)
		}
	}
	return response.Data.Capabilities.Commands, nil
}
