package cli

// errorCodeDefinition is the single published definition of one error or
// failure code: its meaning and the commands whose paths can emit it. The
// guidance fields in the catalog are derived from the runtime classifier.
type errorCodeDefinition struct {
	Code     string
	Meaning  string
	Commands []string
}

var (
	errorScopeAll       = []string{"*"}
	errorScopeStoreRead = []string{"messages.new", "accounts.list", "mailboxes.list", "mailboxes.resolve", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.thread", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "messages.reply", "messages.forward", "batch"}
	errorScopeDetail    = []string{"messages.get", "messages.raw", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "messages.forward", "batch"}
	errorScopeSearch    = []string{"messages.filter", "messages.search"}
	errorScopeMutation  = []string{"messages.mark", "messages.move", "messages.copy", "messages.delete", "batch"}
	errorScopeIMAPRead  = []string{"messages.new", "messages.get", "messages.raw", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "messages.state", "sync", "batch"}
	errorScopeIMAP      = []string{"messages.new", "messages.get", "messages.raw", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "messages.state", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync", "drafts.send", "drafts.reconcile", "batch"}
	errorScopeIdentity  = []string{"messages.new", "messages.state", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync", "drafts.send", "drafts.reconcile", "batch"}
	errorScopeBinding   = []string{"messages.new", "send.setup", "accounts.list", "messages.state", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync", "drafts.send", "drafts.reconcile", "batch"}
	errorScopeDraft     = []string{"drafts.create", "drafts.list", "drafts.inspect", "drafts.preview", "drafts.edit", "drafts.update", "drafts.discard", "drafts.prune", "drafts.adopt", "drafts.send", "drafts.reconcile", "drafts.handoff", "drafts.handoff-reconcile", "messages.reply", "messages.forward"}
	errorScopeSend      = []string{"drafts.send", "drafts.reconcile"}
	errorScopeHandoff   = []string{"drafts.handoff", "drafts.handoff-reconcile"}
	errorScopeMailApp   = []string{"doctor", "sync", "accounts.list", "mailboxes.list", "messages.list"}
	errorScopeKeychain  = []string{"messages.new", "send.setup", "drafts.send", "drafts.reconcile", "messages.get", "messages.raw", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "messages.state", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync", "batch"}
	errorScopeEditor    = []string{"drafts.edit"}
	errorScopeUpdate    = []string{"update"}
	// errorScopeMailStore lists the commands that open Mail's store.
	errorScopeMailStore = []string{"messages.new", "doctor", "batch", "accounts.list", "mailboxes.list", "mailboxes.resolve", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.state", "messages.thread", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "drafts.reconcile", "messages.reply", "messages.forward", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync"}
	// errorScopeRefs lists the commands that take a message, draft, account,
	// mailbox or cursor reference.
	errorScopeRefs = []string{"messages.new", "batch", "accounts.list", "mailboxes.list", "mailboxes.resolve", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.state", "messages.thread", "attachments.list", "attachments.save", "drafts.create", "drafts.list", "drafts.inspect", "drafts.preview", "drafts.edit", "drafts.handoff", "drafts.update", "drafts.open", "drafts.adopt", "drafts.send", "send.setup", "drafts.reconcile", "drafts.discard", "messages.reply", "messages.forward", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync", "drafts.handoff-reconcile"}
	// errorScopeMailStoreRefs lists the commands whose refs are bound to Mail's store.
	errorScopeMailStoreRefs = []string{"messages.new", "batch", "mailboxes.list", "mailboxes.resolve", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.state", "messages.thread", "attachments.list", "attachments.save", "drafts.open", "drafts.adopt", "messages.reply", "messages.forward", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync"}
	// errorScopeOutputBudget lists the commands with a --max-bytes JSON budget.
	errorScopeOutputBudget = []string{"batch", "accounts.list", "mailboxes.list", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.thread", "attachments.list", "drafts.create", "drafts.list", "drafts.inspect", "drafts.preview", "drafts.edit", "drafts.update", "drafts.open", "drafts.adopt", "messages.reply", "messages.forward"}
	// errorScopeSubcommandFamilies lists the commands reached through a family
	// dispatcher, where a mistyped subcommand returns unknown_command.
	errorScopeSubcommandFamilies = []string{"messages.new", "accounts.list", "mailboxes.list", "mailboxes.resolve", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.state", "messages.thread", "attachments.list", "attachments.save", "drafts.create", "drafts.list", "drafts.inspect", "drafts.preview", "drafts.edit", "drafts.handoff", "drafts.update", "drafts.open", "drafts.adopt", "drafts.send", "send.setup", "drafts.reconcile", "drafts.discard", "drafts.prune", "messages.reply", "messages.forward", "messages.mark", "messages.move", "messages.copy", "messages.delete", "drafts.handoff-reconcile"}
	// errorScopeStatefulRuntime is every command except the pure capabilities and
	// version reports, which initialize no state and open no files.
	errorScopeStatefulRuntime = []string{"messages.new", "update", "doctor", "batch", "accounts.list", "mailboxes.list", "mailboxes.resolve", "messages.list", "messages.filter", "messages.search", "messages.get", "messages.raw", "messages.state", "messages.thread", "attachments.list", "attachments.save", "drafts.create", "drafts.list", "drafts.inspect", "drafts.preview", "drafts.edit", "drafts.handoff", "drafts.update", "drafts.open", "drafts.adopt", "drafts.send", "send.setup", "drafts.reconcile", "drafts.discard", "drafts.prune", "messages.reply", "messages.forward", "messages.mark", "messages.move", "messages.copy", "messages.delete", "sync", "drafts.handoff-reconcile"}
)

var errorCodeDefinitions = []errorCodeDefinition{
	{"account_binding_account_degraded", "The account bound to the sender alias is degraded in the Mail catalog.", errorScopeBinding},
	{"account_binding_ambiguous", "The sender alias is bound to more than one account; pass an explicit account ref.", errorScopeBinding},
	{"account_binding_busy", "Another process holds the account-binding lock.", []string{"send.setup"}},
	{"account_binding_changed", "Binding fields changed while the password was entered; nothing was published.", []string{"send.setup"}},
	{"account_binding_host_invalid", "An explicit SMTP/IMAP host or port is invalid or not a public endpoint.", errorScopeBinding},
	{"account_binding_invalid", "The account binding file or requested binding is invalid.", errorScopeBinding},
	{"account_binding_missing", "No binding exists for the sender alias; run send setup with an account ref.", errorScopeBinding},
	{"account_binding_provider_invalid", "The binding names no supported provider and no complete explicit endpoints.", errorScopeBinding},
	{"account_binding_provider_mismatch", "Sender aliases and credential account resolve to different providers.", errorScopeBinding},
	{"account_binding_stale", "The bound account is no longer enabled or has no supported sender alias.", errorScopeBinding},
	{"account_binding_unavailable", "The account-binding store cannot be read or written.", errorScopeBinding},
	{"account_binding_unsafe", "The binding file or its lock is not a safe regular file.", errorScopeBinding},
	{"account_binding_version_unsupported", "The binding file uses a version this build cannot read.", errorScopeBinding},
	{"account_catalog_incomplete", "The local account catalog could not be read completely.", append([]string{"accounts.list"}, errorScopeIdentity...)},
	{"account_degraded", "The target account is degraded in the local catalog; see its degraded_reason.", errorScopeIdentity},
	{"account_disabled", "The target account is disabled in Mail.app.", errorScopeIdentity},
	{"account_identity_missing", "The account has no provable sender identity or credential binding.", errorScopeIdentity},
	{"account_no_email", "The account has no email address to resolve provider endpoints.", []string{"sync"}},
	{"account_not_found", "The requested account ref does not exist in the local catalog.", []string{"sync", "mailboxes.list", "messages.list", "messages.new"}},
	{"account_reference_corrupt", "A stored account reference is corrupt.", errorScopeIdentity},
	{"account_reference_invalid", "An account reference is malformed or mixes incompatible forms.", errorScopeIdentity},
	{"account_reference_version_unsupported", "An account reference uses a version this build cannot decode.", errorScopeIdentity},
	{"adopt_source_incomplete", "The store draft is not fully downloaded; open it in Mail.app first.", []string{"drafts.adopt"}},
	{"ambiguous_attachment", "The attachment identifier matches more than one part.", []string{"attachments.save", "batch"}},
	{"ambiguous_mail_store_generation", "Several Mail store generations exist without an active-generation marker.", errorScopeMailStore},
	{"ambiguous_mailbox", "The mailbox selector matches several mailboxes; choose a returned ref.", []string{"messages.list", "messages.filter", "messages.search", "mailboxes.resolve", "messages.new"}},
	{"ambiguous_message_source", "Both full and partial local sources exist for one message.", errorScopeDetail},
	{"attachment_changed", "An attachment file changed after it was fingerprinted.", append([]string{"attachments.save"}, errorScopeDraft...)},
	{"attachment_not_downloaded", "Attachment bytes are not downloaded locally and no IMAP source is available.", []string{"attachments.save", "drafts.adopt", "batch"}},
	{"attachment_resource_limit", "External attachment discovery hit its directory or hash bound.", []string{"attachments.list", "attachments.save", "messages.get", "batch"}},
	{"batch_canceled", "A batch item was canceled before it started.", []string{"batch"}},
	{"batch_partial", "One or more batch items did not complete; inspect every item.", []string{"batch"}},
	{"bridge_cleanup_failed", "The Apple Events bridge could not verify cleanup of its process group.", errorScopeMailApp},
	{"capability_schema_invalid", "An embedded command schema failed validation.", []string{"capabilities"}},
	{"compose_automation_unsupported", "Scripted Mail compose is disabled because Mail 16 cannot preserve reviewed content.", []string{"drafts.open"}},
	{"confirmation_required", "The action needs --confirm after explicit user authorization.", []string{"messages.delete", "drafts.send", "drafts.discard", "drafts.handoff-reconcile", "batch"}},
	{"content_export_changed", "The export file changed during verification.", []string{"messages.get", "messages.raw", "drafts.inspect"}},
	{"content_export_too_large", "The content exceeds the 64 MiB export limit.", []string{"messages.get", "messages.raw", "drafts.inspect"}},
	{"content_incomplete", "Message content is incomplete; export requires content_complete:true.", []string{"messages.get", "messages.raw", "drafts.open"}},
	{"content_unavailable", "A consumed send receipt has no draft body to export.", []string{"drafts.inspect"}},
	{"draft_adopt_failed", "Adoption of the store draft failed; inspect retained staging before retry.", []string{"drafts.adopt"}},
	{"draft_busy", "Another operation holds the draft lock; this call changed nothing.", errorScopeDraft},
	{"draft_lock_changed", "The draft lock or directory identity changed during the operation.", errorScopeDraft},
	{"draft_lock_unsafe", "The draft lock path is not a safe regular file.", errorScopeDraft},
	{"draft_mutation_confirmation_required", "The message is in Drafts; close its editor and repeat with --allow-draft.", []string{"messages.mark", "messages.move", "messages.delete", "batch"}},
	{"draft_operation_canceled", "The draft command was canceled before completion.", errorScopeDraft},
	{"draft_outcome_unknown", "A historical native save returned no observed draft.", []string{"drafts.reconcile"}},
	{"draft_postflight_failed", "Verification after a historical native save failed.", []string{"drafts.reconcile"}},
	{"draft_revision_conflict", "The draft changed since the reviewed revision; review and merge first.", []string{"drafts.update", "drafts.edit", "drafts.send", "drafts.reconcile"}},
	{"draft_revision_unavailable", "Legacy send evidence has no reviewed revision; inspect or reconcile only.", errorScopeSend},
	{"draft_save_outcome_unknown", "A historical native save is still unproven; the draft and claim are retained.", []string{"drafts.reconcile"}},
	{"draft_save_reconcile_state_failed", "The historical save claim could not be updated after observation.", []string{"drafts.reconcile"}},
	{"draft_save_reconcile_unavailable", "The selected backend cannot reconcile the historical native save.", []string{"drafts.reconcile"}},
	{"draft_save_retry_blocked", "The draft carries a historical save claim; reconcile or discard it before sending.", []string{"drafts.send"}},
	{"draft_state_error", "Draft state cannot be read or does not match its canonical rendering.", errorScopeDraft},
	{"editor_canceled", "The editor was canceled or terminated by a signal.", errorScopeEditor},
	{"editor_failed", "The editor exited with an error.", errorScopeEditor},
	{"editor_terminal_unavailable", "stdin and the selected output are not on the same foreground terminal.", errorScopeEditor},
	{"editor_unavailable", "No editor is configured; pass --editor or set VISUAL or EDITOR.", errorScopeEditor},
	{"environment_unhealthy", "doctor found a failing readiness check.", []string{"doctor"}},
	{"finalization_failed", "Closing transports or the store failed after the command.", errorScopeStatefulRuntime},
	{"forward_source_incomplete", "The forward source is partial, so its attachments cannot be proven.", []string{"messages.forward"}},
	{"handoff_attachment_changed", "An attachment changed after it was recorded; handoff was not dispatched.", errorScopeHandoff},
	{"handoff_attachment_cleanup_failed", "Staged handoff attachments could not be removed.", errorScopeHandoff},
	{"handoff_attachment_missing", "A recorded attachment is missing; handoff was not dispatched.", errorScopeHandoff},
	{"handoff_attachment_unreadable", "A recorded attachment cannot be read; handoff was not dispatched.", errorScopeHandoff},
	{"handoff_attempt_mismatch", "The attempt ID does not match the retained handoff.", []string{"drafts.handoff-reconcile"}},
	{"handoff_canceled_before_dispatch", "Handoff was canceled before native dispatch; no compose window opened.", []string{"drafts.handoff"}},
	{"handoff_claim_cleanup_failed", "The handoff claim could not be removed after completion.", errorScopeHandoff},
	{"handoff_not_dispatched", "The retained handoff has no dispatch to reconcile.", []string{"drafts.handoff-reconcile"}},
	{"handoff_not_found", "No retained handoff exists for this draft.", []string{"drafts.handoff-reconcile"}},
	{"handoff_outcome_unknown", "Handoff ended after dispatch without a confirmed result; inspect Mail.app and reconcile.", []string{"drafts.handoff"}},
	{"handoff_response_invalid", "The native handoff reported success without a dispatch boundary.", []string{"drafts.handoff"}},
	{"handoff_retry_blocked", "A retained handoff attempt blocks a new handoff until it is reconciled.", []string{"drafts.handoff"}},
	{"handoff_session_closed", "The handoff session was already closed.", []string{"drafts.handoff"}},
	{"hydration_failed", "Targeted IMAP hydration of missing content failed; local evidence is retained.", errorScopeIMAPRead},
	{"imap_account_busy", "Another process holds the account's IMAP mutation lock; nothing was sent.", append(append([]string{}, errorScopeMutation...), "drafts.send", "drafts.reconcile")},
	{"imap_ambiguous_mailbox", "Several server mailboxes match the requested role or name.", errorScopeIMAP},
	{"imap_ambiguous_message_id", "Several server messages match the Message-ID; no UID was targeted.", errorScopeIMAP},
	{"imap_append_failed", "The server rejected the Sent APPEND.", errorScopeSend},
	{"imap_append_incomplete", "The Sent APPEND stopped before its terminator; reconcile may retry it.", errorScopeSend},
	{"imap_append_outcome_unknown", "The Sent APPEND may have been stored; reconcile verifies, never re-appends.", errorScopeSend},
	{"imap_auth_failed", "IMAP rejected the stored app-specific password.", errorScopeIMAP},
	{"imap_canceled", "The IMAP command was canceled.", errorScopeIMAP},
	{"imap_command_rejected", "The server rejected an IMAP command; see error.imap_rejection.", errorScopeIMAP},
	{"imap_connect_failed", "The IMAP connection or TLS verification failed.", errorScopeIMAP},
	{"imap_copy_outcome_unknown", "A COPY response was lost; observe the destination before any retry.", []string{"messages.copy", "messages.move", "messages.delete", "batch"}},
	{"imap_credentials_missing", "No IMAP credential or account identity is configured.", errorScopeIMAP},
	{"imap_disconnected", "The IMAP connection dropped.", errorScopeIMAP},
	{"imap_fetch_failed", "An IMAP FETCH failed.", errorScopeIMAPRead},
	{"imap_flag_read_unsupported", "The configured transport cannot read server flags.", []string{"messages.state"}},
	{"imap_flags_mismatch", "Observed server flags contradict the requested change.", []string{"messages.mark", "batch"}},
	{"imap_flags_outcome_unknown", "Flag changes could not be verified after STORE.", []string{"messages.mark", "messages.move", "messages.delete", "batch"}},
	{"imap_flags_partial", "Only some flag phases were applied.", []string{"messages.mark", "batch"}},
	{"imap_flags_unsupported", "The mailbox does not permit the required flag change.", []string{"messages.mark", "messages.move", "messages.delete", "batch"}},
	{"imap_mailbox_not_found", "The server has no mailbox with the resolved name.", errorScopeIMAP},
	{"imap_message_not_found", "The target message no longer exists on the server.", errorScopeIMAP},
	{"imap_message_uid_mismatch", "The server UID does not match the verified message identity.", errorScopeIMAP},
	{"imap_message_uid_unknown", "No verified server UID exists for the message.", errorScopeIMAP},
	{"imap_move_outcome_unknown", "A native or fallback MOVE has unverified effects; observe both mailboxes before any retry.", []string{"messages.move", "messages.delete", "batch"}},
	{"imap_mutation_failed", "An IMAP mutation failed with an origin-ambiguous error; inspect before replay.", errorScopeMutation},
	{"imap_mutation_lock_unavailable", "The cross-process IMAP mutation lock could not be set up; nothing was sent.", append(append([]string{}, errorScopeMutation...), "drafts.send", "drafts.reconcile")},
	{"imap_quota_exceeded", "The target mailbox is over quota.", errorScopeIMAP},
	{"imap_resource_limit_exceeded", "A LIST or APPEND response exceeded its bound; see error.limit.", errorScopeIMAP},
	{"imap_response_malformed", "The server sent a malformed IMAP response.", errorScopeIMAP},
	{"imap_sent_mailbox_not_found", "No Sent mailbox could be resolved on the server.", errorScopeSend},
	{"imap_timeout", "An IMAP command timed out.", errorScopeIMAP},
	{"initialization_failed", "MailCLI could not initialize its configuration or state.", errorScopeStatefulRuntime},
	{"interactive_required", "drafts edit needs an interactive terminal; agents use drafts update.", errorScopeEditor},
	{"invalid_address", "An email address has invalid syntax.", append(append([]string{}, errorScopeDraft...), "send.setup")},
	{"invalid_argument", "A flag, positional argument or combination is invalid.", errorScopeAll},
	{"invalid_cursor", "The cursor is malformed or no longer matches the listing; restart without it.", []string{"accounts.list", "mailboxes.list", "messages.list", "messages.filter", "messages.search", "messages.thread", "attachments.list", "drafts.list"}},
	{"invalid_editor", "The editor command is invalid.", errorScopeEditor},
	{"invalid_emlx", "A local .emlx source has invalid framing.", errorScopeDetail},
	{"invalid_imap_value", "A Message-ID or IMAP value is malformed.", errorScopeIMAP},
	{"invalid_input", "Structured JSON input is malformed or has unknown, duplicate or invalid fields.", []string{"drafts.create", "drafts.update", "messages.reply", "messages.forward", "drafts.edit", "batch"}},
	{"invalid_mailbox_cache", "A mailbox cache file cannot be inspected.", errorScopeStoreRead},
	{"invalid_message_source", "The source message has invalid structure, headers or no reply target.", []string{"messages.reply", "messages.forward", "messages.get", "attachments.list", "attachments.save", "drafts.send"}},
	{"invalid_path_segment", "A mailbox path contains an unsafe segment.", errorScopeStoreRead},
	{"invalid_reference", "A ref is malformed; use a current ref from a listing.", errorScopeRefs},
	{"keychain_delete_failed", "The Keychain credential could not be deleted.", []string{"send.setup"}},
	{"keychain_invalid_identifier", "The credential account identifier contains a NUL byte.", errorScopeKeychain},
	{"keychain_item_duplicate", "The Keychain already holds a conflicting item.", []string{"send.setup"}},
	{"keychain_item_not_found", "No Keychain credential exists for the account.", errorScopeKeychain},
	{"keychain_load_failed", "The Keychain credential could not be read.", errorScopeKeychain},
	{"keychain_store_failed", "The Keychain credential could not be stored.", []string{"send.setup"}},
	{"keychain_unsupported", "This build has no Keychain support.", errorScopeKeychain},
	{"list_identity_invalid", "A listing returned a missing or duplicate stable identity.", []string{"accounts.list", "mailboxes.list", "attachments.list"}},
	{"local_only_mailbox", "The mailbox exists only locally, so IMAP cannot reach it.", errorScopeIMAP},
	{"mail_access_gate_corrupt", "MailCLI's Mail.app recovery state is invalid; quit Mail.app and retry.", errorScopeMailApp},
	{"mail_access_gate_failed", "The Mail.app access gate could not be acquired.", errorScopeMailApp},
	{"mail_access_gate_unsafe", "The access-gate path is unsafe; nothing was dispatched.", errorScopeMailApp},
	{"mail_automation_unavailable", "The Mail.app automation backend is unavailable.", errorScopeMailApp},
	{"mail_busy", "Another MailCLI operation holds the Mail.app gate; this request did not start.", errorScopeMailApp},
	{"mail_not_running", "Mail.app is not running; open it and retry.", errorScopeMailApp},
	{"mail_recovery_required", "A previous Mail.app operation may still be running; quit and reopen Mail.app.", errorScopeMailApp},
	{"mail_service_unavailable", "The mail service is not available to the batch.", []string{"batch"}},
	{"mail_store_not_read_only", "The Envelope Index connection is not query-only.", errorScopeMailStore},
	{"mail_store_path_mismatch", "The opened Envelope Index is not the verified store path.", errorScopeMailStore},
	{"mail_store_preferences_invalid", "Mail's account ordering preferences are invalid.", errorScopeStoreRead},
	{"mail_store_preferences_unavailable", "Mail's account ordering preferences cannot be read.", errorScopeStoreRead},
	{"mail_store_unavailable", "The local Mail store is unavailable, usually missing Full Disk Access.", errorScopeStoreRead},
	{"mailbox_cache_malformed", "A mailbox cache file is malformed (reported as degraded_reason mailbox_cache_unreadable).", []string{"accounts.list", "mailboxes.list"}},
	{"mailbox_catalog_incomplete", "The mailbox catalog could not be read completely.", errorScopeStoreRead},
	{"mailbox_info_malformed", "A mailbox Info.plist is malformed.", errorScopeStoreRead},
	{"mailbox_uidvalidity_changed", "The mailbox UIDVALIDITY changed; resolve a fresh ref.", errorScopeIMAP},
	{"mailbox_uidvalidity_unknown", "The mailbox UIDVALIDITY is unknown.", errorScopeIMAP},
	{"message_already_trashed", "The message is already in Trash.", []string{"messages.delete", "batch"}},
	{"message_source_missing", "The message source is not downloaded locally.", errorScopeDetail},
	{"mime_resource_limit", "MIME parsing hit its aggregate resource budget.", errorScopeDetail},
	{"not_found", "The requested message, draft, mailbox or attachment does not exist.", errorScopeRefs},
	{"operation_canceled", "The operation was canceled.", errorScopeStatefulRuntime},
	{"operation_failed", "A runtime failure without a more specific code.", errorScopeAll},
	{"operation_timeout", "The operation exceeded its deadline.", errorScopeStatefulRuntime},
	{"output_too_large", "The JSON response exceeds --max-bytes; narrow fields, export or raise the budget.", errorScopeOutputBudget},
	{"prune_candidate_limit_exceeded", "Prune classification exceeded its 64 MiB metadata bound; nothing was removed.", []string{"drafts.prune"}},
	{"prune_failed", "One or more prune candidates could not be removed.", []string{"drafts.prune"}},
	{"prune_state_changed", "The draft directory changed before cleanup; nothing was removed.", []string{"drafts.prune"}},
	{"raw_source_partial", "Only a partial local source exists; exact raw source needs a complete one.", []string{"messages.raw", "messages.get", "batch"}},
	{"raw_source_too_large", "The raw message source exceeds 64 MiB.", errorScopeDetail},
	{"safe_mailbox_listing_unavailable", "Mailbox listing needs the supported local store; no Apple Events scan is used.", []string{"mailboxes.list", "mailboxes.resolve"}},
	{"safe_message_listing_unavailable", "Unified inbox and mailbox selectors need the supported local store.", []string{"messages.list"}},
	{"safe_search_unavailable", "Search needs the supported local store; no Apple Events scan is used.", errorScopeSearch},
	{"safe_write_unavailable", "Verified mutation needs the supported read-only local store.", errorScopeMutation},
	{"search_budget_too_small", "The next source does not fit the scan budget; retry with error.required_bytes.", errorScopeSearch},
	{"search_count_limit_exceeded", "The exact candidate count exceeds its bound; narrow the search.", errorScopeSearch},
	{"search_cursor_stale", "The Envelope Index changed since the previous page; restart the search.", errorScopeSearch},
	{"search_index_changed", "The Envelope Index changed during this page; retry the page.", errorScopeSearch},
	{"search_unavailable", "The selected backend does not support safe search.", errorScopeSearch},
	{"send_cleanup_failed", "Local send-state cleanup failed after terminal evidence.", errorScopeSend},
	{"send_fingerprint_mismatch", "The Sent candidate or draft no longer matches the claimed MIME fingerprint.", errorScopeSend},
	{"send_identity_mismatch", "The Sent candidate does not match the claimed identity.", errorScopeSend},
	{"send_identity_unreadable", "The Sent candidate cannot be read for identity verification.", errorScopeSend},
	{"send_identity_unverifiable", "The claim lacks the identity needed for verification.", errorScopeSend},
	{"send_materialization_invalid", "Mail.app returned no final native body for historical observation.", []string{"drafts.reconcile"}},
	{"send_materialization_missing", "Mail.app returned no final native headers and body for historical observation.", []string{"drafts.reconcile"}},
	{"send_mirror_outcome_unknown", "A Sent APPEND may have stored the message; reconcile verifies it.", errorScopeSend},
	{"send_mirror_pending", "SMTP accepted the message but the Sent copy is incomplete; run drafts reconcile.", errorScopeSend},
	{"send_not_observed", "A historical send request is not yet proven by SMTP or Sent evidence.", errorScopeSend},
	{"send_outcome_unknown", "The send outcome is unknown; the claim blocks replay until reconciled.", errorScopeSend},
	{"send_outcome_unverifiable", "No Sent evidence can prove the send; resolve manually.", errorScopeSend},
	{"send_receipt_conflict", "A different immutable send receipt already exists.", errorScopeSend},
	{"send_receipt_expired", "The terminal send receipt has expired.", append([]string{"drafts.inspect"}, errorScopeSend...)},
	{"send_receipt_invalid", "The send receipt is not a bounded regular file.", append([]string{"drafts.inspect", "drafts.prune"}, errorScopeSend...)},
	{"send_receipt_persist_failed", "The send receipt could not be written.", errorScopeSend},
	{"send_receipt_unavailable", "No send receipt is available for the consumed draft.", append([]string{"drafts.inspect"}, errorScopeSend...)},
	{"send_reconcile_state_failed", "The send claim could not be updated after reconciliation.", errorScopeSend},
	{"send_reconcile_unavailable", "Reconciliation cannot run for this claim (no Message-ID or usable UID).", errorScopeSend},
	{"send_recovery_spool_changed", "The recovery spool changed or an unclaimed spool blocks sending.", errorScopeSend},
	{"send_recovery_spool_invalid", "Recovery spool metadata is invalid.", errorScopeSend},
	{"send_recovery_spool_missing", "The accepted-message recovery spool is missing.", errorScopeSend},
	{"send_recovery_spool_persist_failed", "The recovery spool could not be written; nothing was submitted.", []string{"drafts.send"}},
	{"send_recovery_spool_unavailable", "No recovery spool is retained, so the mirror cannot be retried automatically.", errorScopeSend},
	{"send_retry_blocked", "The draft already has a send attempt; inspect or reconcile instead of retrying.", []string{"drafts.send"}},
	{"send_state_cleanup_failed", "Transient send state could not be cleared.", errorScopeSend},
	{"send_state_unknown", "The send claim state is unknown.", errorScopeSend},
	{"send_transport_unavailable", "No direct SMTP transport is configured.", errorScopeSend},
	{"serialization_failed", "The command output could not be serialized.", errorScopeAll},
	{"smtp_auth_failed", "SMTP rejected the stored app-specific password.", []string{"drafts.send"}},
	{"smtp_credentials_missing", "No app-specific password is stored; run send setup.", []string{"drafts.send"}},
	{"smtp_data_incomplete", "SMTP DATA stopped before the terminator; no acceptance occurred.", []string{"drafts.send"}},
	{"smtp_rejected", "The SMTP server rejected the message with a final 4xx/5xx reply.", []string{"drafts.send"}},
	{"smtp_source_invalid", "The composed source was short, oversized or unreadable before the terminator.", []string{"drafts.send"}},
	{"smtp_submission_unknown", "SMTP may have accepted the message; retain the claim and reconcile.", []string{"drafts.send"}},
	{"smtp_timeout", "An SMTP command timed out.", []string{"drafts.send"}},
	{"smtp_tls_failed", "The SMTP TLS handshake or verification failed.", []string{"drafts.send"}},
	{"smtp_transfer_timeout", "The SMTP DATA transfer exceeded its budget.", []string{"drafts.send"}},
	{"smtp_utf8_unsupported", "The server lacks SMTPUTF8/8BITMIME for internationalized addresses or headers.", []string{"drafts.send"}},
	{"special_use_mailbox_unresolved", "An account's special-use mailbox could not be resolved (degraded_reason).", []string{"accounts.list"}},
	{"stale_reference", "The ref no longer matches the store; resolve a fresh ref.", errorScopeMailStoreRefs},
	{"store_bound_reference_required", "The command needs a store-bound message ref from the local store.", []string{"messages.reply", "messages.forward", "messages.get", "batch"}},
	{"store_changed", "The Mail store or an attachment changed during the operation.", errorScopeStoreRead},
	{"store_profile_unverified", "The store framework version is unverified; reads continue (data.store_profile.code).", errorScopeStoreRead},
	{"sync_check_local_messages_unavailable", "Local counts for a mailbox are unavailable (data.sync_check.failures).", []string{"sync"}},
	{"sync_check_missing_local_mailbox", "A server mailbox has no local counterpart (data.sync_check.failures).", []string{"sync"}},
	{"sync_check_server_catalog_incomplete", "The server mailbox list is incomplete (data.sync_check.failures).", []string{"sync"}},
	{"transport_unsupported_provider", "The provider has no built-in endpoints and no explicit binding hosts.", errorScopeBinding},
	{"unknown_command", "The command or subcommand does not exist.", errorScopeSubcommandFamilies},
	{"unsafe_message_source", "A local source or output path failed safety checks.", errorScopeStoreRead},
	{"unsupported_mail_store_schema", "The Mail store version or schema is not supported.", errorScopeMailStore},
	{"unsupported_platform", "The platform cannot provide the required safe file access.", errorScopeStatefulRuntime},
	{"update_busy", "Another installation holds the update lock.", errorScopeUpdate},
	{"update_check_failed", "Release metadata could not be fetched or parsed.", errorScopeUpdate},
	{"update_checksum_invalid", "SHA256SUMS is malformed.", errorScopeUpdate},
	{"update_checksum_mismatch", "The archive does not match SHA256SUMS.", errorScopeUpdate},
	{"update_download_failed", "A release asset could not be downloaded.", errorScopeUpdate},
	{"update_host_untrusted", "A release URL points outside the trusted GitHub hosts.", errorScopeUpdate},
	{"update_install_failed", "The verified package could not be installed; see data.update_result.", errorScopeUpdate},
	{"update_lock_failed", "The update lock could not be set up.", errorScopeUpdate},
	{"update_package_invalid", "The release package or binary failed verification.", errorScopeUpdate},
	{"update_package_missing", "The latest release lacks a required asset.", errorScopeUpdate},
	{"update_redirect_invalid", "A release redirect is malformed.", errorScopeUpdate},
	{"update_redirect_limit", "A release download exceeded the redirect limit.", errorScopeUpdate},
	{"update_signature_invalid", "The SHA256SUMS signature is invalid.", errorScopeUpdate},
	{"update_unsupported_platform", "Self-update requires darwin/arm64.", errorScopeUpdate},
	{"update_url_insecure", "A release URL is not HTTPS.", errorScopeUpdate},
	{"update_url_invalid", "A release URL is malformed.", errorScopeUpdate},
	{"update_url_invalid_port", "A release URL uses a non-default port.", errorScopeUpdate},
}
